### ISSUE TITLE
No intellisense for files imported from node_modules

### ISSUE THREAD

**Issue by Legends** [mrmlnc/vscode-scss#110]
- VS Code Version: latest
- SCSS IntelliSense Version: latest
- Operating System: Win 10

`Visual Studio reference comments: // <reference path="./references.scss" />.`
I have this references.scss file which imports local scss files, but it also import scss from node_modules folder.

I only get intellisense for local scss file though.

**Comment by jercodes** [comment]
+1

This extension does not suggest variables from imported files.

**Comment by mrmlnc** [comment]
Sorry, the references support was removed in [commit](https://github.com/mrmlnc/vscode-scss/commit/cc348c876ae1e7d1394001a3121b15d4b67bf353#diff-b7ecc6f2f32a4fc4bdbf497aff710f1cL14) due to the fact that the new parser (`vscode-css-languageservice`) does not support this format. I have no plans to support reference comments, please use the native import mechanism.

I forgot to write about this in the release and fix the documentation.
